#!/data/data/com.termux/files/usr/bin/bash -e

termux-setup-storage

pkg install wget nano ecj dx curl mariadb openssh clang libusb python3 -y
pkg install ocl-icd opencl-headers opencl-clhpp clvk clpeak -y
pkg install termux-api x11-repo root-repo unstable-repo libusb cmatrix neofetch nyancat screenfetch -y

sh -c "$(curl -fsSL https://github.com/Cabbagec/termux-ohmyzsh/raw/master/install.sh)"

ln -s /data/data/com.termux/files/home/storage/shared/tencent/QQfile_recv QQ

wget -O https://raw.githubusercontent.com/kimocoder/termux-nethunter/master/install-nethunter-termux
chmod +x install-nethunter-termux
./install-nethunter-termux

# Database fix
# ---------------------------------
# Log on to Termux users
#mysql -u $(whoami)

# SQL statement to modify root password
#use mysql;
#set password for 'root'@'localhost' = password('toor');

# Refresh permissions and exit
#flush privileges;
#quit;

#mysql -u root -p

#grant all on *.* to root@'%' identified by 'toor' with grant option;
#flush privileges;

#pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start

cmatrix
